# Generated by Django 3.2.16 on 2022-11-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='Uniq user subscription',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'subscription'), name='Unique user subscription'),
        ),
    ]
