# Generated by Django 3.2.16 on 2022-12-01 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221128_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
