name: foodgram_workflow

on:
  push:
    branches:
    - master
    pull_request:

jobs:
  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: './backend/requirements.txt'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install pytest pytest-cov pytest-django pytest-mock

    - name: Install Requirements
      run: pip install -r ./backend/requirements.txt

    - name: Run tests and collect coverage
      run: |
        cd backend
        python -m flake8 .
        python -m pytest --cov --verbose --color=yes --cov-report=xml .

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: /home/runner/work/foodgram-project-react/foodgram-project-react/backend/coverage.xml
